import useTranslation from "next-translate/useTranslation";
import { Metadata, NextPage } from "next";
import HeroBanner from "@/components/Banner/HeroBanner";
import ServiceBanner from "@/components/Banner/ServiceBanner";
import WebDev from "@/components/Icon/WebDev";

const Home: NextPage = () => {
  const { t } = useTranslation();

  return (
    <div className='flex flex-col items-center justify-start'>
      <HeroBanner />
      <ServiceBanner
        services={[
          {
            icon: <WebDev />,
            caption: `"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet,
        consectetur, adipisci velit..." "There is no one who loves pain
        itself, who seeks after it and wants to have it, simply because it
        is pain..."`,
          },
          {
            icon: <WebDev />,
            caption: `"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet,
        consectetur, adipisci velit..." "There is no one who loves pain
        itself, who seeks after it and wants to have it, simply because it
        is pain..."`,
          },
          {
            icon: <WebDev />,
            caption: `"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet,
        consectetur, adipisci velit..." "There is no one who loves pain
        itself, who seeks after it and wants to have it, simply because it
        is pain..."`,
          },
          {
            icon: <WebDev />,
            caption: `"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet,
        consectetur, adipisci velit..." "There is no one who loves pain
        itself, who seeks after it and wants to have it, simply because it
        is pain..."`,
          },
        ]}
      />
    </div>
  );
};

export default Home;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
